config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :lists

  root 'lists#new'
  post '/lists' => 'lists#create'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many  :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @task = Task.new
  end

  # GET /lists/new
  def new
    @task = Task.new
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.js
        format.html { redirect_to root_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :priority, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VladTaskMaster</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <h1><%= link_to 'Vlad the Task Impaler', root_path%></h1>

  <%= yield %>

  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list, :html => { id: 'add_list' }, remote: true)  do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Add a new list:</p></br>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: 'list_title' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="list">
  <h2>
    <button class="destroy-list"><%= link_to 'X', list, method: :delete, data: { confirm: 'Are you sure?' } %></button><%= @list.title %>
  </h2>
  <ul id="list-<%= @list.id %>" data-id="<%= @list.id %>">
  </ul>
</div>

app/views/lists/_new_list.html.erb
<form id="add_list" action="/lists" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <label for="list_title">Add a new list:</label>
  <input type="text" id="list_title" name="title" placeholder="title">
  <input type="submit" value="(+) add">
</form><!-- #add_list -->

app/views/lists/create.js.erb
$("#lists").append("<%=j render @list %>");
$("#list_title").val("");

app/views/lists/edit.html.erb
<h2>Edit list title</h2>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h2>task lists</h2>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.title, list %> 
      <%= link_to 'Edit', edit_list_path(list) %> 
      <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a New List', new_list_path %>

app/views/lists/new.html.erb
<h2>Create a new list</h2>

<%= render 'form' %>
<%= render 'tasks/form' %>


<section id="lists">
  <% @lists.each do |list| %>
    <div class="list">
  <h2>
    <button class="destroy-list"><%= link_to 'X', list, method: :delete, data: { confirm: 'Are you sure?' } %></button><%= list.title %>
  </h2>
  <ul id="list-<%= list.id %>" data-id="<%= list.id %>">
    <% list.tasks.each do |task| %>
    <p>
    <button class="destroy-task"><%= link_to 'X', task, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    Task:<%= task.description %><br />
    Priority: <%= task.priority %>
    </p>

    <br>
    <% end %>
  </ul>
</div>
  <% end %>
</section>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @list.title %></h2>
<ul>
<% @list.tasks.each do |task| %>
  <li>Task: <%= task.description %></li>
  <li>Priority: <%= task.priority %></li>
<% end %>
</ul>

<p><%= link_to 'Edit Title', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>
</p>
</br>

<%= render 'tasks/form' %>

app/views/tasks/_add_tasks.html.erb
  <form id="add_task" action="#" method="post">
    <p>Add a task:</p></br>
    <label for="task_description">Task description:</label>
    <input type="text" id="task_description" name="task_description" placeholder="description">
    <label for="task_priority">Priority level:</label>
    <input type="text" id="task_priority" name="task_priority" placeholder="priority">
    <input type="submit" value="(+) add">
  </form><!-- #add_task -->

app/views/tasks/_form.html.erb
<%= form_for(@task, :html => { id: 'add_task' }, :remote => true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Add a new task:</p></br>

  <div class="field">
  <%= f.collection_select :list_id, List.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, id: 'task_description' %>
  </div>
  <div class="field">
    <%= f.label :priority %>
    <%= f.text_field :priority, id: 'task_priority'%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_tasks.html.erb
 <p>
    <button class="destroy-task"><%= link_to 'X', task, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    Task:<%= task.description %><br />
    Priority: <%= task.priority %>
</p>

app/views/tasks/create.js.erb
$("#list-<%=j render @list.id%>").append("<%=j render @task %>");
$("#task_description").val("");
$("#task_priority").val("");

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Priority</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.list_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>List:</strong>
  <%= @task.list_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>